### ISSUE TITLE
Editor: Mapping properties cut on to small window

### ISSUE THREAD

**Issue by luckydonald** [ponyorm/pony-doc#1]
You guys should add a scrollbar to the **Mapping Properties** pane in the ER editor.

![screen_shot_2016-10-19_at_18_34_59](https://cloud.githubusercontent.com/assets/2737108/19528257/8c43b0e4-962b-11e6-90a6-826bf5707808.png)

Fix by adding

``` css
overflow: scroll;
```

to `#sidebar`

**Edit:** Can't reproduce that fix now, but the error still persists.

**Comment by luckydonald** [comment]
I just have a 13'' laptop, so that gets very annoying. 
Problem in Firefox, Chrome and Safari.
Mac OS 10.9.5

**Comment by amalashkevich** [comment]
Thank you @luckydonald!
Should be fixed now.
